### ISSUE TITLE
Install the new admin database servers 

### ISSUE THREAD

**Issue by carlosadean** [linea-it/idac_db#1]
The current databases servers for administrative databases are obsolete and need to be upgraded.

```[tasklist]
### Tasks - Phase 1
- [ ] Install and configure the primary server with PostgreSQL (vm)
- [ ] Install and configure the secondary server with PostgreSQL (vm)
- [ ] Configure Postgres archiving and replication
- [ ] Configure Postgres hot-standby
- [ ] Document a hot-standby operational procedure
```
```[tasklist]
### Tasks - Phase 2
- [ ] Import the databases in the new server
- [ ] Configure the applications to use the new servers
- [ ] Configure logical backups
```
